name: Testing Docker Image

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker test
      run: |
        docker -v
        docker ps -a
